AWSTemplateFormatVersion: "2010-09-09"
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: "keep track of used projects commitIds"

  CdcLegalConservationStreamRetentionHours:
    Type: Number
    Description: "Change Data Capture Kinesis Data Stream retention period in hours"
    Default: "72"

  CdcLegalConservationStreamShardCount:
    Type: Number
    Default: "0"

  CdcLegalConservationStreamMode:
    Description: Stream Mode.
    Default: ON_DEMAND
    Type: String
    AllowedValues: [ON_DEMAND, PROVISIONED]

  SafeStorageEventStreamShardCount:
    Type: Number
    Default: "0"

  SafeStorageEventStreamMode:
    Description: Stream Mode.
    Default: ON_DEMAND
    Type: String
    AllowedValues: [ON_DEMAND, PROVISIONED]

  LegalConservationEventUpdateStreamShardCount:
    Type: Number
    Default: "0"

  LegalConservationEventUpdateStreamMode:
    Description: Stream Mode.
    Default: ON_DEMAND
    Type: String
    AllowedValues: [ON_DEMAND, PROVISIONED]

  AlarmSNSTopicName:
    Type: String
    Description: "Topic alarm"

  LogRetention:
    Type: Number
    Default: 14

Conditions:
  CdcLegalConservationOnDemandDisabled: !Not [!Equals [!Ref CdcLegalConservationStreamMode, ON_DEMAND]]
  LegalConservationEventUpdateOnDemandDisabled: !Not [!Equals [!Ref LegalConservationEventUpdateStreamMode, ON_DEMAND]]
  SafeStorageEventOnDemandeDisabled: !Not [!Equals [!Ref SafeStorageEventStreamMode, ON_DEMAND]]

Resources:
  # KINESIS SOURCE STREAM FOR Change Data Capture
  ## AWS KMS / Server-side encryption for Kinesis Stream 
  CdcLegalConservationKinesisServerSideEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  SafeStorageEventKinesisServerSideEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  LegalConservationEventUpdateKinesisServerSideEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  ## Kinesis Data Stream 
  CdcLegalConservationKinesisStream:
    Type: AWS::Kinesis::Stream
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub "${ProjectName}-cdc-legal-conservation-stream-001"
      RetentionPeriodHours: !Ref CdcLegalConservationStreamRetentionHours
      ShardCount: !If [CdcLegalConservationOnDemandDisabled, !Ref CdcLegalConservationStreamShardCount, !Ref "AWS::NoValue"]
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Fn::GetAtt:
            - CdcLegalConservationKinesisServerSideEncryptionKey
            - Arn
      StreamModeDetails:
        StreamMode: !Ref CdcLegalConservationStreamMode   

  LegalConservationUpdateKinesisStream:
    Type: AWS::Kinesis::Stream
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub "${ProjectName}-legal-conservation-event-update-stream-001"
      RetentionPeriodHours: 8760 # 365 days
      ShardCount: !If [LegalConservationEventUpdateOnDemandDisabled, !Ref LegalConservationEventUpdateStreamShardCount, !Ref "AWS::NoValue"]
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Fn::GetAtt:
            - LegalConservationEventUpdateKinesisServerSideEncryptionKey
            - Arn
      StreamModeDetails:
        StreamMode: !Ref LegalConservationEventUpdateStreamMode   

  SafeStorageEventKinesisStream:
    Type: AWS::Kinesis::Stream
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub "${ProjectName}-safe-storage-event-stream"
      RetentionPeriodHours: 720 # 30 days
      ShardCount: !If [SafeStorageEventOnDemandeDisabled, !Ref SafeStorageEventStreamShardCount, !Ref "AWS::NoValue"]
      StreamEncryption:
        EncryptionType: KMS
        KeyId:
          Fn::GetAtt:
            - SafeStorageEventKinesisServerSideEncryptionKey
            - Arn
      StreamModeDetails:
        StreamMode: !Ref SafeStorageEventStreamMode  

  LegalConservationRequestTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TableName: !Sub "${ProjectName}-legal-conservation-request"
      AttributeDefinitions:
        # primary key
        - AttributeName: "pk" # entity type (req or sla violation) concatenated to fileKey
          AttributeType: "S"
        - AttributeName: "sk" # entity type (req or sla violation) concatenated to fileKey
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "sla_TTL"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KinesisStreamSpecification:
        StreamArn: !GetAtt CdcLegalConservationKinesisStream.Arn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  LegalConservationRequestHistoryTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TableName: !Sub "${ProjectName}-legal-conservation-request-history"
      AttributeDefinitions:
        # primary key
        - AttributeName: "pk" # entity type (req or sla violation) concatenated to document type
          AttributeType: "S"
        - AttributeName: "sk" # string concatenation based on step type
          AttributeType: "S"
        - AttributeName: "errorResponseTimestampYearMonth"
          AttributeType: "S"
        - AttributeName: "errorResponseTimestamp"
          AttributeType: "S"
        - AttributeName: "entityName_externalId"
          AttributeType: "S"
        - AttributeName: "sk_entityName_externalId"
          AttributeType: "S"
        - AttributeName: "errorCode_errorResponseTimestampYearMonth"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        -
          IndexName: "sortBy-errorTimestamp"
          KeySchema:
            -
              AttributeName: "errorResponseTimestampYearMonth"
              KeyType: "HASH"
            - 
              AttributeName: "errorResponseTimestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"                     
        -
          IndexName: "by-externalId"
          KeySchema:
            -
              AttributeName: "entityName_externalId"
              KeyType: "HASH"
            - 
              AttributeName: "sk_entityName_externalId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"            
        -
          IndexName: "by-errorCode"
          KeySchema:
            -
              AttributeName: "errorCode_errorResponseTimestampYearMonth"
              KeyType: "HASH"
            - 
              AttributeName: "errorResponseTimestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"                                 
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "delete_TTL"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  # SQS Queue
  SafeStorageListenerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub "${ProjectName}-cn-safe-storage-listener-stream-dlq"
        DelaySeconds: 10
        HasDLQ: "false"
        QueueHasAlarm: "true"
        AlarmSNSTopicName: !Ref AlarmSNSTopicName

  LegalConservationTrackerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-legal_conservation_tracker_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  LegalConservationStarterLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-legalConservationStarter"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

  PreSignedUrlGeneratorLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-preSignedUrlGenerator"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

  EventUpdateReceiverLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-eventUpdateRecevier"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

  LegalConservationTrackerLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-legalConservationTracker"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:
  LegalConservationRequestDynamoTableName:
    Description: Name of dynamodb table containing notifications metadata
    Value: !Ref LegalConservationRequestTable
  LegalConservationRequestDynamoTableArn:
    Description: ARN of dynamodb table containing notifications metadata
    Value: !Sub "${LegalConservationRequestTable.Arn}"

  LegalConservationRequestHistoryDynamoTableName:
    Description: Name of dynamodb table containing notifications metadata
    Value: !Ref LegalConservationRequestHistoryTable
  LegalConservationRequestHistoryDynamoTableArn:
    Description: ARN of dynamodb table containing notifications metadata
    Value: !Sub "${LegalConservationRequestHistoryTable.Arn}"

  # Kinesis Source Stream containing the DynamoDB Change Data Capture events
  CdcLegalConservationKinesisSourceStreamArn:
    Description: "Kinesis source CDC stream ARN"
    Value: !GetAtt CdcLegalConservationKinesisStream.Arn
  CdcLegalConservationKinesisSourceStreamName:
    Description: "Kinesis source CDC stream Name"
    Value: !Ref CdcLegalConservationKinesisStream
  CdcLegalConservationKinesisSourceStreamKeyArn:
    Description: "Kinesis source CDC stream crypto key ARN"
    Value: !GetAtt CdcLegalConservationKinesisServerSideEncryptionKey.Arn

  LegalConservationUpdateKinesisStreamArn:
    Value: !GetAtt LegalConservationUpdateKinesisStream.Arn
  LegalConservationUpdateKinesisStreamName:
    Value: !Ref LegalConservationUpdateKinesisStream
  LegalConservationUpdateKinesisStreamKeyArn:
    Value: !GetAtt LegalConservationEventUpdateKinesisServerSideEncryptionKey.Arn

  SafeStorageEventKinesisStreamArn:
    Value: !GetAtt SafeStorageEventKinesisStream.Arn
  SafeStorageEventKinesisStreamName:
    Value: !Ref SafeStorageEventKinesisStream
  SafeStorageEventKinesisStreamKeyArn:
    Value: !GetAtt SafeStorageEventKinesisServerSideEncryptionKey.Arn

  LegalConservationTrackerDLQName:
    Value: !GetAtt LegalConservationTrackerDLQ.Outputs.QueueName
    Description: queue name
  LegalConservationTrackerDLQURL:
    Value: !GetAtt LegalConservationTrackerDLQ.Outputs.QueueURL
    Description: e URL
  LegalConservationTrackerDLQARN:
    Value: !GetAtt LegalConservationTrackerDLQ.Outputs.QueueARN
    Description: queue ARN
  LegalConservationTrackerDLQAlarmARN:
    Value: !GetAtt LegalConservationTrackerDLQ.Outputs.SqsDLQAlarmArn
    Description: alarm ARN

  SafeStorageListenerDLQName:
    Value: !GetAtt SafeStorageListenerDLQ.Outputs.QueueName
    Description: queue name
  SafeStorageListenerDLQURL:
    Value: !GetAtt SafeStorageListenerDLQ.Outputs.QueueURL
    Description: e URL
  SafeStorageListenerDLQARN:
    Value: !GetAtt SafeStorageListenerDLQ.Outputs.QueueARN
    Description: queue ARN
  SafeStorageListenerDLQAlarmARN:
    Value: !GetAtt SafeStorageListenerDLQ.Outputs.SqsDLQAlarmArn
    Description: alarm ARN

  # Lambda functions
  SafeStorageListenerLambdaName:
    Value: !Sub "${ProjectName}-legalConservationStarter"

  PreSignedUrlGeneratorLambdaName:
    Value: !Sub "${ProjectName}-preSignedUrlGenerator"

  EventUpdateReceiverLambdaName:
    Value: !Sub "${ProjectName}-eventUpdateRecevier"

  LegalConservationTrackerLambdaName:
    Value: !Sub "${ProjectName}-legalConservationTracker"
